// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "zilo/backend/api/internal/handler/auth"
	workflows "zilo/backend/api/internal/handler/workflows"
	"zilo/backend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: auth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/me",
				Handler: auth.MeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/executions/:executionId",
				Handler: workflows.GetExecutionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/executions/:executionId/logs",
				Handler: workflows.GetExecutionLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/workflows",
				Handler: workflows.CreateWorkflowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/workflows",
				Handler: workflows.ListWorkflowsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/workflows/:id",
				Handler: workflows.GetWorkflowHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/workflows/:id",
				Handler: workflows.UpdateWorkflowHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/workflows/:id",
				Handler: workflows.DeleteWorkflowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/workflows/:id/debug",
				Handler: workflows.DebugWorkflowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/workflows/:id/draft",
				Handler: workflows.SaveWorkflowDraftHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/workflows/:id/execute",
				Handler: workflows.ExecuteWorkflowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/workflows/:id/publish",
				Handler: workflows.PublishWorkflowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/workflows/:id/rollback/:version",
				Handler: workflows.RollbackWorkflowVersionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/workflows/:id/versions",
				Handler: workflows.ListWorkflowVersionsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
