// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: rpc/workflow/workflow.proto

package workflowpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,3,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResp) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type RefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	ExpireAt      int64                  `protobuf:"varint,2,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResp) Reset() {
	*x = RefreshTokenResp{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResp) ProtoMessage() {}

func (x *RefreshTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResp.ProtoReflect.Descriptor instead.
func (*RefreshTokenResp) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshTokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResp) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type MeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeReq) Reset() {
	*x = MeReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeReq) ProtoMessage() {}

func (x *MeReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeReq.ProtoReflect.Descriptor instead.
func (*MeReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *MeReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeResp) Reset() {
	*x = MeResp{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeResp) ProtoMessage() {}

func (x *MeResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeResp.ProtoReflect.Descriptor instead.
func (*MeResp) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *MeResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MeResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MeResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type CreateWorkflowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowReq) Reset() {
	*x = CreateWorkflowReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowReq) ProtoMessage() {}

func (x *CreateWorkflowReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowReq.ProtoReflect.Descriptor instead.
func (*CreateWorkflowReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *CreateWorkflowReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateWorkflowReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkflowReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type WorkflowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	LatestVersion int64                  `protobuf:"varint,5,opt,name=latestVersion,proto3" json:"latestVersion,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResp) Reset() {
	*x = WorkflowResp{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResp) ProtoMessage() {}

func (x *WorkflowResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResp.ProtoReflect.Descriptor instead.
func (*WorkflowResp) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *WorkflowResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkflowResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkflowResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WorkflowResp) GetLatestVersion() int64 {
	if x != nil {
		return x.LatestVersion
	}
	return 0
}

func (x *WorkflowResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WorkflowResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListWorkflowsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsReq) Reset() {
	*x = ListWorkflowsReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsReq) ProtoMessage() {}

func (x *ListWorkflowsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsReq.ProtoReflect.Descriptor instead.
func (*ListWorkflowsReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *ListWorkflowsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListWorkflowsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWorkflowsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkflowsReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ListWorkflowsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*WorkflowResp        `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResp) Reset() {
	*x = ListWorkflowsResp{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResp) ProtoMessage() {}

func (x *ListWorkflowsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResp.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResp) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *ListWorkflowsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListWorkflowsResp) GetList() []*WorkflowResp {
	if x != nil {
		return x.List
	}
	return nil
}

type WorkflowByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	WorkflowId    int64                  `protobuf:"varint,2,opt,name=workflowId,proto3" json:"workflowId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowByIdReq) Reset() {
	*x = WorkflowByIdReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowByIdReq) ProtoMessage() {}

func (x *WorkflowByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowByIdReq.ProtoReflect.Descriptor instead.
func (*WorkflowByIdReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *WorkflowByIdReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WorkflowByIdReq) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

type UpdateWorkflowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	WorkflowId    int64                  `protobuf:"varint,2,opt,name=workflowId,proto3" json:"workflowId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkflowReq) Reset() {
	*x = UpdateWorkflowReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkflowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkflowReq) ProtoMessage() {}

func (x *UpdateWorkflowReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkflowReq.ProtoReflect.Descriptor instead.
func (*UpdateWorkflowReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateWorkflowReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateWorkflowReq) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *UpdateWorkflowReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWorkflowReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{14}
}

type SaveDraftReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	WorkflowId    int64                  `protobuf:"varint,2,opt,name=workflowId,proto3" json:"workflowId,omitempty"`
	DslJson       string                 `protobuf:"bytes,3,opt,name=dslJson,proto3" json:"dslJson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDraftReq) Reset() {
	*x = SaveDraftReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDraftReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDraftReq) ProtoMessage() {}

func (x *SaveDraftReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDraftReq.ProtoReflect.Descriptor instead.
func (*SaveDraftReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{15}
}

func (x *SaveDraftReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SaveDraftReq) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *SaveDraftReq) GetDslJson() string {
	if x != nil {
		return x.DslJson
	}
	return ""
}

type PublishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	WorkflowId    int64                  `protobuf:"varint,2,opt,name=workflowId,proto3" json:"workflowId,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReq) Reset() {
	*x = PublishReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReq) ProtoMessage() {}

func (x *PublishReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReq.ProtoReflect.Descriptor instead.
func (*PublishReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{16}
}

func (x *PublishReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishReq) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *PublishReq) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type PublishResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResp) Reset() {
	*x = PublishResp{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResp) ProtoMessage() {}

func (x *PublishResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResp.ProtoReflect.Descriptor instead.
func (*PublishResp) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{17}
}

func (x *PublishResp) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ListVersionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	WorkflowId    int64                  `protobuf:"varint,2,opt,name=workflowId,proto3" json:"workflowId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsReq) Reset() {
	*x = ListVersionsReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsReq) ProtoMessage() {}

func (x *ListVersionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsReq.ProtoReflect.Descriptor instead.
func (*ListVersionsReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{18}
}

func (x *ListVersionsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListVersionsReq) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

type VersionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	IsPublished   bool                   `protobuf:"varint,3,opt,name=isPublished,proto3" json:"isPublished,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionItem) Reset() {
	*x = VersionItem{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionItem) ProtoMessage() {}

func (x *VersionItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionItem.ProtoReflect.Descriptor instead.
func (*VersionItem) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{19}
}

func (x *VersionItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VersionItem) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VersionItem) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *VersionItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListVersionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*VersionItem         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVersionsResp) Reset() {
	*x = ListVersionsResp{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVersionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResp) ProtoMessage() {}

func (x *ListVersionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResp.ProtoReflect.Descriptor instead.
func (*ListVersionsResp) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{20}
}

func (x *ListVersionsResp) GetList() []*VersionItem {
	if x != nil {
		return x.List
	}
	return nil
}

type RollbackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	WorkflowId    int64                  `protobuf:"varint,2,opt,name=workflowId,proto3" json:"workflowId,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackReq) Reset() {
	*x = RollbackReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackReq) ProtoMessage() {}

func (x *RollbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackReq.ProtoReflect.Descriptor instead.
func (*RollbackReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{21}
}

func (x *RollbackReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RollbackReq) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *RollbackReq) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ExecuteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	WorkflowId    int64                  `protobuf:"varint,2,opt,name=workflowId,proto3" json:"workflowId,omitempty"`
	InputJson     string                 `protobuf:"bytes,3,opt,name=inputJson,proto3" json:"inputJson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteReq) Reset() {
	*x = ExecuteReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteReq) ProtoMessage() {}

func (x *ExecuteReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteReq.ProtoReflect.Descriptor instead.
func (*ExecuteReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{22}
}

func (x *ExecuteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ExecuteReq) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *ExecuteReq) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type ExecuteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   int64                  `protobuf:"varint,1,opt,name=executionId,proto3" json:"executionId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResp) Reset() {
	*x = ExecuteResp{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResp) ProtoMessage() {}

func (x *ExecuteResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResp.ProtoReflect.Descriptor instead.
func (*ExecuteResp) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{23}
}

func (x *ExecuteResp) GetExecutionId() int64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *ExecuteResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ExecutionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ExecutionId   int64                  `protobuf:"varint,2,opt,name=executionId,proto3" json:"executionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionReq) Reset() {
	*x = ExecutionReq{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionReq) ProtoMessage() {}

func (x *ExecutionReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionReq.ProtoReflect.Descriptor instead.
func (*ExecutionReq) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{24}
}

func (x *ExecutionReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ExecutionReq) GetExecutionId() int64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

type ExecutionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId    int64                  `protobuf:"varint,2,opt,name=workflowId,proto3" json:"workflowId,omitempty"`
	VersionId     int64                  `protobuf:"varint,3,opt,name=versionId,proto3" json:"versionId,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	InputJson     string                 `protobuf:"bytes,5,opt,name=inputJson,proto3" json:"inputJson,omitempty"`
	OutputJson    string                 `protobuf:"bytes,6,opt,name=outputJson,proto3" json:"outputJson,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,7,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	StartedAt     string                 `protobuf:"bytes,8,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	EndedAt       string                 `protobuf:"bytes,9,opt,name=endedAt,proto3" json:"endedAt,omitempty"`
	DurationMs    int64                  `protobuf:"varint,10,opt,name=durationMs,proto3" json:"durationMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResp) Reset() {
	*x = ExecutionResp{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResp) ProtoMessage() {}

func (x *ExecutionResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResp.ProtoReflect.Descriptor instead.
func (*ExecutionResp) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{25}
}

func (x *ExecutionResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExecutionResp) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *ExecutionResp) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *ExecutionResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionResp) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *ExecutionResp) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *ExecutionResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ExecutionResp) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ExecutionResp) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

func (x *ExecutionResp) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ExecutionLogItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=nodeType,proto3" json:"nodeType,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	InputJson     string                 `protobuf:"bytes,4,opt,name=inputJson,proto3" json:"inputJson,omitempty"`
	OutputJson    string                 `protobuf:"bytes,5,opt,name=outputJson,proto3" json:"outputJson,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,6,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	StartedAt     string                 `protobuf:"bytes,7,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	EndedAt       string                 `protobuf:"bytes,8,opt,name=endedAt,proto3" json:"endedAt,omitempty"`
	DurationMs    int64                  `protobuf:"varint,9,opt,name=durationMs,proto3" json:"durationMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionLogItem) Reset() {
	*x = ExecutionLogItem{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionLogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionLogItem) ProtoMessage() {}

func (x *ExecutionLogItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionLogItem.ProtoReflect.Descriptor instead.
func (*ExecutionLogItem) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{26}
}

func (x *ExecutionLogItem) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecutionLogItem) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *ExecutionLogItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionLogItem) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *ExecutionLogItem) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *ExecutionLogItem) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ExecutionLogItem) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ExecutionLogItem) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

func (x *ExecutionLogItem) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type ExecutionLogsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ExecutionLogItem    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionLogsResp) Reset() {
	*x = ExecutionLogsResp{}
	mi := &file_rpc_workflow_workflow_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionLogsResp) ProtoMessage() {}

func (x *ExecutionLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_workflow_workflow_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionLogsResp.ProtoReflect.Descriptor instead.
func (*ExecutionLogsResp) Descriptor() ([]byte, []int) {
	return file_rpc_workflow_workflow_proto_rawDescGZIP(), []int{27}
}

func (x *ExecutionLogsResp) GetList() []*ExecutionLogItem {
	if x != nil {
		return x.List
	}
	return nil
}

var File_rpc_workflow_workflow_proto protoreflect.FileDescriptor

const file_rpc_workflow_workflow_proto_rawDesc = "" +
	"\n" +
	"\x1brpc/workflow/workflow.proto\x12\bworkflow\"[\n" +
	"\vRegisterReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\"<\n" +
	"\fRegisterResp\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"<\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"m\n" +
	"\tLoginResp\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12\x1a\n" +
	"\bexpireAt\x18\x03 \x01(\x03R\bexpireAt\"5\n" +
	"\x0fRefreshTokenReq\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\tR\frefreshToken\"P\n" +
	"\x10RefreshTokenResp\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x1a\n" +
	"\bexpireAt\x18\x02 \x01(\x03R\bexpireAt\"\x1f\n" +
	"\x05MeReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"R\n" +
	"\x06MeResp\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\"a\n" +
	"\x11CreateWorkflowReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xce\x01\n" +
	"\fWorkflowResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\x12$\n" +
	"\rlatestVersion\x18\x05 \x01(\x03R\rlatestVersion\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\a \x01(\tR\tupdatedAt\"t\n" +
	"\x10ListWorkflowsReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\"U\n" +
	"\x11ListWorkflowsResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12*\n" +
	"\x04list\x18\x02 \x03(\v2\x16.workflow.WorkflowRespR\x04list\"I\n" +
	"\x0fWorkflowByIdReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"workflowId\x18\x02 \x01(\x03R\n" +
	"workflowId\"\x81\x01\n" +
	"\x11UpdateWorkflowReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"workflowId\x18\x02 \x01(\x03R\n" +
	"workflowId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\a\n" +
	"\x05Empty\"`\n" +
	"\fSaveDraftReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"workflowId\x18\x02 \x01(\x03R\n" +
	"workflowId\x12\x18\n" +
	"\adslJson\x18\x03 \x01(\tR\adslJson\"X\n" +
	"\n" +
	"PublishReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"workflowId\x18\x02 \x01(\x03R\n" +
	"workflowId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"'\n" +
	"\vPublishResp\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"I\n" +
	"\x0fListVersionsReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"workflowId\x18\x02 \x01(\x03R\n" +
	"workflowId\"w\n" +
	"\vVersionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12 \n" +
	"\visPublished\x18\x03 \x01(\bR\visPublished\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\"=\n" +
	"\x10ListVersionsResp\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.workflow.VersionItemR\x04list\"_\n" +
	"\vRollbackReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"workflowId\x18\x02 \x01(\x03R\n" +
	"workflowId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"b\n" +
	"\n" +
	"ExecuteReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"workflowId\x18\x02 \x01(\x03R\n" +
	"workflowId\x12\x1c\n" +
	"\tinputJson\x18\x03 \x01(\tR\tinputJson\"G\n" +
	"\vExecuteResp\x12 \n" +
	"\vexecutionId\x18\x01 \x01(\x03R\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"H\n" +
	"\fExecutionReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12 \n" +
	"\vexecutionId\x18\x02 \x01(\x03R\vexecutionId\"\xa7\x02\n" +
	"\rExecutionResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"workflowId\x18\x02 \x01(\x03R\n" +
	"workflowId\x12\x1c\n" +
	"\tversionId\x18\x03 \x01(\x03R\tversionId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\tinputJson\x18\x05 \x01(\tR\tinputJson\x12\x1e\n" +
	"\n" +
	"outputJson\x18\x06 \x01(\tR\n" +
	"outputJson\x12\x1a\n" +
	"\berrorMsg\x18\a \x01(\tR\berrorMsg\x12\x1c\n" +
	"\tstartedAt\x18\b \x01(\tR\tstartedAt\x12\x18\n" +
	"\aendedAt\x18\t \x01(\tR\aendedAt\x12\x1e\n" +
	"\n" +
	"durationMs\x18\n" +
	" \x01(\x03R\n" +
	"durationMs\"\x90\x02\n" +
	"\x10ExecutionLogItem\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bnodeType\x18\x02 \x01(\tR\bnodeType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\tinputJson\x18\x04 \x01(\tR\tinputJson\x12\x1e\n" +
	"\n" +
	"outputJson\x18\x05 \x01(\tR\n" +
	"outputJson\x12\x1a\n" +
	"\berrorMsg\x18\x06 \x01(\tR\berrorMsg\x12\x1c\n" +
	"\tstartedAt\x18\a \x01(\tR\tstartedAt\x12\x18\n" +
	"\aendedAt\x18\b \x01(\tR\aendedAt\x12\x1e\n" +
	"\n" +
	"durationMs\x18\t \x01(\x03R\n" +
	"durationMs\"C\n" +
	"\x11ExecutionLogsResp\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.workflow.ExecutionLogItemR\x04list2\xda\b\n" +
	"\vWorkflowRpc\x129\n" +
	"\bRegister\x12\x15.workflow.RegisterReq\x1a\x16.workflow.RegisterResp\x120\n" +
	"\x05Login\x12\x12.workflow.LoginReq\x1a\x13.workflow.LoginResp\x12E\n" +
	"\fRefreshToken\x12\x19.workflow.RefreshTokenReq\x1a\x1a.workflow.RefreshTokenResp\x12'\n" +
	"\x02Me\x12\x0f.workflow.MeReq\x1a\x10.workflow.MeResp\x12E\n" +
	"\x0eCreateWorkflow\x12\x1b.workflow.CreateWorkflowReq\x1a\x16.workflow.WorkflowResp\x12H\n" +
	"\rListWorkflows\x12\x1a.workflow.ListWorkflowsReq\x1a\x1b.workflow.ListWorkflowsResp\x12@\n" +
	"\vGetWorkflow\x12\x19.workflow.WorkflowByIdReq\x1a\x16.workflow.WorkflowResp\x12E\n" +
	"\x0eUpdateWorkflow\x12\x1b.workflow.UpdateWorkflowReq\x1a\x16.workflow.WorkflowResp\x12<\n" +
	"\x0eDeleteWorkflow\x12\x19.workflow.WorkflowByIdReq\x1a\x0f.workflow.Empty\x12<\n" +
	"\x11SaveWorkflowDraft\x12\x16.workflow.SaveDraftReq\x1a\x0f.workflow.Empty\x12>\n" +
	"\x0fPublishWorkflow\x12\x14.workflow.PublishReq\x1a\x15.workflow.PublishResp\x12M\n" +
	"\x14ListWorkflowVersions\x12\x19.workflow.ListVersionsReq\x1a\x1a.workflow.ListVersionsResp\x12A\n" +
	"\x17RollbackWorkflowVersion\x12\x15.workflow.RollbackReq\x1a\x0f.workflow.Empty\x12>\n" +
	"\x0fExecuteWorkflow\x12\x14.workflow.ExecuteReq\x1a\x15.workflow.ExecuteResp\x12<\n" +
	"\rDebugWorkflow\x12\x14.workflow.ExecuteReq\x1a\x15.workflow.ExecuteResp\x12?\n" +
	"\fGetExecution\x12\x16.workflow.ExecutionReq\x1a\x17.workflow.ExecutionResp\x12G\n" +
	"\x10GetExecutionLogs\x12\x16.workflow.ExecutionReq\x1a\x1b.workflow.ExecutionLogsRespB\x0eZ\f./workflowpbb\x06proto3"

var (
	file_rpc_workflow_workflow_proto_rawDescOnce sync.Once
	file_rpc_workflow_workflow_proto_rawDescData []byte
)

func file_rpc_workflow_workflow_proto_rawDescGZIP() []byte {
	file_rpc_workflow_workflow_proto_rawDescOnce.Do(func() {
		file_rpc_workflow_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_workflow_workflow_proto_rawDesc), len(file_rpc_workflow_workflow_proto_rawDesc)))
	})
	return file_rpc_workflow_workflow_proto_rawDescData
}

var file_rpc_workflow_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_rpc_workflow_workflow_proto_goTypes = []any{
	(*RegisterReq)(nil),       // 0: workflow.RegisterReq
	(*RegisterResp)(nil),      // 1: workflow.RegisterResp
	(*LoginReq)(nil),          // 2: workflow.LoginReq
	(*LoginResp)(nil),         // 3: workflow.LoginResp
	(*RefreshTokenReq)(nil),   // 4: workflow.RefreshTokenReq
	(*RefreshTokenResp)(nil),  // 5: workflow.RefreshTokenResp
	(*MeReq)(nil),             // 6: workflow.MeReq
	(*MeResp)(nil),            // 7: workflow.MeResp
	(*CreateWorkflowReq)(nil), // 8: workflow.CreateWorkflowReq
	(*WorkflowResp)(nil),      // 9: workflow.WorkflowResp
	(*ListWorkflowsReq)(nil),  // 10: workflow.ListWorkflowsReq
	(*ListWorkflowsResp)(nil), // 11: workflow.ListWorkflowsResp
	(*WorkflowByIdReq)(nil),   // 12: workflow.WorkflowByIdReq
	(*UpdateWorkflowReq)(nil), // 13: workflow.UpdateWorkflowReq
	(*Empty)(nil),             // 14: workflow.Empty
	(*SaveDraftReq)(nil),      // 15: workflow.SaveDraftReq
	(*PublishReq)(nil),        // 16: workflow.PublishReq
	(*PublishResp)(nil),       // 17: workflow.PublishResp
	(*ListVersionsReq)(nil),   // 18: workflow.ListVersionsReq
	(*VersionItem)(nil),       // 19: workflow.VersionItem
	(*ListVersionsResp)(nil),  // 20: workflow.ListVersionsResp
	(*RollbackReq)(nil),       // 21: workflow.RollbackReq
	(*ExecuteReq)(nil),        // 22: workflow.ExecuteReq
	(*ExecuteResp)(nil),       // 23: workflow.ExecuteResp
	(*ExecutionReq)(nil),      // 24: workflow.ExecutionReq
	(*ExecutionResp)(nil),     // 25: workflow.ExecutionResp
	(*ExecutionLogItem)(nil),  // 26: workflow.ExecutionLogItem
	(*ExecutionLogsResp)(nil), // 27: workflow.ExecutionLogsResp
}
var file_rpc_workflow_workflow_proto_depIdxs = []int32{
	9,  // 0: workflow.ListWorkflowsResp.list:type_name -> workflow.WorkflowResp
	19, // 1: workflow.ListVersionsResp.list:type_name -> workflow.VersionItem
	26, // 2: workflow.ExecutionLogsResp.list:type_name -> workflow.ExecutionLogItem
	0,  // 3: workflow.WorkflowRpc.Register:input_type -> workflow.RegisterReq
	2,  // 4: workflow.WorkflowRpc.Login:input_type -> workflow.LoginReq
	4,  // 5: workflow.WorkflowRpc.RefreshToken:input_type -> workflow.RefreshTokenReq
	6,  // 6: workflow.WorkflowRpc.Me:input_type -> workflow.MeReq
	8,  // 7: workflow.WorkflowRpc.CreateWorkflow:input_type -> workflow.CreateWorkflowReq
	10, // 8: workflow.WorkflowRpc.ListWorkflows:input_type -> workflow.ListWorkflowsReq
	12, // 9: workflow.WorkflowRpc.GetWorkflow:input_type -> workflow.WorkflowByIdReq
	13, // 10: workflow.WorkflowRpc.UpdateWorkflow:input_type -> workflow.UpdateWorkflowReq
	12, // 11: workflow.WorkflowRpc.DeleteWorkflow:input_type -> workflow.WorkflowByIdReq
	15, // 12: workflow.WorkflowRpc.SaveWorkflowDraft:input_type -> workflow.SaveDraftReq
	16, // 13: workflow.WorkflowRpc.PublishWorkflow:input_type -> workflow.PublishReq
	18, // 14: workflow.WorkflowRpc.ListWorkflowVersions:input_type -> workflow.ListVersionsReq
	21, // 15: workflow.WorkflowRpc.RollbackWorkflowVersion:input_type -> workflow.RollbackReq
	22, // 16: workflow.WorkflowRpc.ExecuteWorkflow:input_type -> workflow.ExecuteReq
	22, // 17: workflow.WorkflowRpc.DebugWorkflow:input_type -> workflow.ExecuteReq
	24, // 18: workflow.WorkflowRpc.GetExecution:input_type -> workflow.ExecutionReq
	24, // 19: workflow.WorkflowRpc.GetExecutionLogs:input_type -> workflow.ExecutionReq
	1,  // 20: workflow.WorkflowRpc.Register:output_type -> workflow.RegisterResp
	3,  // 21: workflow.WorkflowRpc.Login:output_type -> workflow.LoginResp
	5,  // 22: workflow.WorkflowRpc.RefreshToken:output_type -> workflow.RefreshTokenResp
	7,  // 23: workflow.WorkflowRpc.Me:output_type -> workflow.MeResp
	9,  // 24: workflow.WorkflowRpc.CreateWorkflow:output_type -> workflow.WorkflowResp
	11, // 25: workflow.WorkflowRpc.ListWorkflows:output_type -> workflow.ListWorkflowsResp
	9,  // 26: workflow.WorkflowRpc.GetWorkflow:output_type -> workflow.WorkflowResp
	9,  // 27: workflow.WorkflowRpc.UpdateWorkflow:output_type -> workflow.WorkflowResp
	14, // 28: workflow.WorkflowRpc.DeleteWorkflow:output_type -> workflow.Empty
	14, // 29: workflow.WorkflowRpc.SaveWorkflowDraft:output_type -> workflow.Empty
	17, // 30: workflow.WorkflowRpc.PublishWorkflow:output_type -> workflow.PublishResp
	20, // 31: workflow.WorkflowRpc.ListWorkflowVersions:output_type -> workflow.ListVersionsResp
	14, // 32: workflow.WorkflowRpc.RollbackWorkflowVersion:output_type -> workflow.Empty
	23, // 33: workflow.WorkflowRpc.ExecuteWorkflow:output_type -> workflow.ExecuteResp
	23, // 34: workflow.WorkflowRpc.DebugWorkflow:output_type -> workflow.ExecuteResp
	25, // 35: workflow.WorkflowRpc.GetExecution:output_type -> workflow.ExecutionResp
	27, // 36: workflow.WorkflowRpc.GetExecutionLogs:output_type -> workflow.ExecutionLogsResp
	20, // [20:37] is the sub-list for method output_type
	3,  // [3:20] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_workflow_workflow_proto_init() }
func file_rpc_workflow_workflow_proto_init() {
	if File_rpc_workflow_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_workflow_workflow_proto_rawDesc), len(file_rpc_workflow_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_workflow_workflow_proto_goTypes,
		DependencyIndexes: file_rpc_workflow_workflow_proto_depIdxs,
		MessageInfos:      file_rpc_workflow_workflow_proto_msgTypes,
	}.Build()
	File_rpc_workflow_workflow_proto = out.File
	file_rpc_workflow_workflow_proto_goTypes = nil
	file_rpc_workflow_workflow_proto_depIdxs = nil
}
