// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: rpc/workflow/workflow.proto

package workflowpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowRpc_Register_FullMethodName                = "/workflow.WorkflowRpc/Register"
	WorkflowRpc_Login_FullMethodName                   = "/workflow.WorkflowRpc/Login"
	WorkflowRpc_RefreshToken_FullMethodName            = "/workflow.WorkflowRpc/RefreshToken"
	WorkflowRpc_Me_FullMethodName                      = "/workflow.WorkflowRpc/Me"
	WorkflowRpc_CreateWorkflow_FullMethodName          = "/workflow.WorkflowRpc/CreateWorkflow"
	WorkflowRpc_ListWorkflows_FullMethodName           = "/workflow.WorkflowRpc/ListWorkflows"
	WorkflowRpc_GetWorkflow_FullMethodName             = "/workflow.WorkflowRpc/GetWorkflow"
	WorkflowRpc_UpdateWorkflow_FullMethodName          = "/workflow.WorkflowRpc/UpdateWorkflow"
	WorkflowRpc_DeleteWorkflow_FullMethodName          = "/workflow.WorkflowRpc/DeleteWorkflow"
	WorkflowRpc_SaveWorkflowDraft_FullMethodName       = "/workflow.WorkflowRpc/SaveWorkflowDraft"
	WorkflowRpc_PublishWorkflow_FullMethodName         = "/workflow.WorkflowRpc/PublishWorkflow"
	WorkflowRpc_ListWorkflowVersions_FullMethodName    = "/workflow.WorkflowRpc/ListWorkflowVersions"
	WorkflowRpc_RollbackWorkflowVersion_FullMethodName = "/workflow.WorkflowRpc/RollbackWorkflowVersion"
	WorkflowRpc_ExecuteWorkflow_FullMethodName         = "/workflow.WorkflowRpc/ExecuteWorkflow"
	WorkflowRpc_DebugWorkflow_FullMethodName           = "/workflow.WorkflowRpc/DebugWorkflow"
	WorkflowRpc_GetExecution_FullMethodName            = "/workflow.WorkflowRpc/GetExecution"
	WorkflowRpc_GetExecutionLogs_FullMethodName        = "/workflow.WorkflowRpc/GetExecutionLogs"
)

// WorkflowRpcClient is the client API for WorkflowRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowRpcClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
	Me(ctx context.Context, in *MeReq, opts ...grpc.CallOption) (*MeResp, error)
	CreateWorkflow(ctx context.Context, in *CreateWorkflowReq, opts ...grpc.CallOption) (*WorkflowResp, error)
	ListWorkflows(ctx context.Context, in *ListWorkflowsReq, opts ...grpc.CallOption) (*ListWorkflowsResp, error)
	GetWorkflow(ctx context.Context, in *WorkflowByIdReq, opts ...grpc.CallOption) (*WorkflowResp, error)
	UpdateWorkflow(ctx context.Context, in *UpdateWorkflowReq, opts ...grpc.CallOption) (*WorkflowResp, error)
	DeleteWorkflow(ctx context.Context, in *WorkflowByIdReq, opts ...grpc.CallOption) (*Empty, error)
	SaveWorkflowDraft(ctx context.Context, in *SaveDraftReq, opts ...grpc.CallOption) (*Empty, error)
	PublishWorkflow(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResp, error)
	ListWorkflowVersions(ctx context.Context, in *ListVersionsReq, opts ...grpc.CallOption) (*ListVersionsResp, error)
	RollbackWorkflowVersion(ctx context.Context, in *RollbackReq, opts ...grpc.CallOption) (*Empty, error)
	ExecuteWorkflow(ctx context.Context, in *ExecuteReq, opts ...grpc.CallOption) (*ExecuteResp, error)
	DebugWorkflow(ctx context.Context, in *ExecuteReq, opts ...grpc.CallOption) (*ExecuteResp, error)
	GetExecution(ctx context.Context, in *ExecutionReq, opts ...grpc.CallOption) (*ExecutionResp, error)
	GetExecutionLogs(ctx context.Context, in *ExecutionReq, opts ...grpc.CallOption) (*ExecutionLogsResp, error)
}

type workflowRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowRpcClient(cc grpc.ClientConnInterface) WorkflowRpcClient {
	return &workflowRpcClient{cc}
}

func (c *workflowRpcClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) Me(ctx context.Context, in *MeReq, opts ...grpc.CallOption) (*MeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_Me_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) CreateWorkflow(ctx context.Context, in *CreateWorkflowReq, opts ...grpc.CallOption) (*WorkflowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_CreateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) ListWorkflows(ctx context.Context, in *ListWorkflowsReq, opts ...grpc.CallOption) (*ListWorkflowsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkflowsResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_ListWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) GetWorkflow(ctx context.Context, in *WorkflowByIdReq, opts ...grpc.CallOption) (*WorkflowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_GetWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) UpdateWorkflow(ctx context.Context, in *UpdateWorkflowReq, opts ...grpc.CallOption) (*WorkflowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_UpdateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) DeleteWorkflow(ctx context.Context, in *WorkflowByIdReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WorkflowRpc_DeleteWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) SaveWorkflowDraft(ctx context.Context, in *SaveDraftReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WorkflowRpc_SaveWorkflowDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) PublishWorkflow(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_PublishWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) ListWorkflowVersions(ctx context.Context, in *ListVersionsReq, opts ...grpc.CallOption) (*ListVersionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVersionsResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_ListWorkflowVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) RollbackWorkflowVersion(ctx context.Context, in *RollbackReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WorkflowRpc_RollbackWorkflowVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) ExecuteWorkflow(ctx context.Context, in *ExecuteReq, opts ...grpc.CallOption) (*ExecuteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_ExecuteWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) DebugWorkflow(ctx context.Context, in *ExecuteReq, opts ...grpc.CallOption) (*ExecuteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_DebugWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) GetExecution(ctx context.Context, in *ExecutionReq, opts ...grpc.CallOption) (*ExecutionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_GetExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowRpcClient) GetExecutionLogs(ctx context.Context, in *ExecutionReq, opts ...grpc.CallOption) (*ExecutionLogsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionLogsResp)
	err := c.cc.Invoke(ctx, WorkflowRpc_GetExecutionLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowRpcServer is the server API for WorkflowRpc service.
// All implementations must embed UnimplementedWorkflowRpcServer
// for forward compatibility.
type WorkflowRpcServer interface {
	Register(context.Context, *RegisterReq) (*RegisterResp, error)
	Login(context.Context, *LoginReq) (*LoginResp, error)
	RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenResp, error)
	Me(context.Context, *MeReq) (*MeResp, error)
	CreateWorkflow(context.Context, *CreateWorkflowReq) (*WorkflowResp, error)
	ListWorkflows(context.Context, *ListWorkflowsReq) (*ListWorkflowsResp, error)
	GetWorkflow(context.Context, *WorkflowByIdReq) (*WorkflowResp, error)
	UpdateWorkflow(context.Context, *UpdateWorkflowReq) (*WorkflowResp, error)
	DeleteWorkflow(context.Context, *WorkflowByIdReq) (*Empty, error)
	SaveWorkflowDraft(context.Context, *SaveDraftReq) (*Empty, error)
	PublishWorkflow(context.Context, *PublishReq) (*PublishResp, error)
	ListWorkflowVersions(context.Context, *ListVersionsReq) (*ListVersionsResp, error)
	RollbackWorkflowVersion(context.Context, *RollbackReq) (*Empty, error)
	ExecuteWorkflow(context.Context, *ExecuteReq) (*ExecuteResp, error)
	DebugWorkflow(context.Context, *ExecuteReq) (*ExecuteResp, error)
	GetExecution(context.Context, *ExecutionReq) (*ExecutionResp, error)
	GetExecutionLogs(context.Context, *ExecutionReq) (*ExecutionLogsResp, error)
	mustEmbedUnimplementedWorkflowRpcServer()
}

// UnimplementedWorkflowRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowRpcServer struct{}

func (UnimplementedWorkflowRpcServer) Register(context.Context, *RegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedWorkflowRpcServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedWorkflowRpcServer) RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedWorkflowRpcServer) Me(context.Context, *MeReq) (*MeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Me not implemented")
}
func (UnimplementedWorkflowRpcServer) CreateWorkflow(context.Context, *CreateWorkflowReq) (*WorkflowResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkflow not implemented")
}
func (UnimplementedWorkflowRpcServer) ListWorkflows(context.Context, *ListWorkflowsReq) (*ListWorkflowsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkflows not implemented")
}
func (UnimplementedWorkflowRpcServer) GetWorkflow(context.Context, *WorkflowByIdReq) (*WorkflowResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflow not implemented")
}
func (UnimplementedWorkflowRpcServer) UpdateWorkflow(context.Context, *UpdateWorkflowReq) (*WorkflowResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWorkflow not implemented")
}
func (UnimplementedWorkflowRpcServer) DeleteWorkflow(context.Context, *WorkflowByIdReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkflow not implemented")
}
func (UnimplementedWorkflowRpcServer) SaveWorkflowDraft(context.Context, *SaveDraftReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveWorkflowDraft not implemented")
}
func (UnimplementedWorkflowRpcServer) PublishWorkflow(context.Context, *PublishReq) (*PublishResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishWorkflow not implemented")
}
func (UnimplementedWorkflowRpcServer) ListWorkflowVersions(context.Context, *ListVersionsReq) (*ListVersionsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkflowVersions not implemented")
}
func (UnimplementedWorkflowRpcServer) RollbackWorkflowVersion(context.Context, *RollbackReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackWorkflowVersion not implemented")
}
func (UnimplementedWorkflowRpcServer) ExecuteWorkflow(context.Context, *ExecuteReq) (*ExecuteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteWorkflow not implemented")
}
func (UnimplementedWorkflowRpcServer) DebugWorkflow(context.Context, *ExecuteReq) (*ExecuteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DebugWorkflow not implemented")
}
func (UnimplementedWorkflowRpcServer) GetExecution(context.Context, *ExecutionReq) (*ExecutionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecution not implemented")
}
func (UnimplementedWorkflowRpcServer) GetExecutionLogs(context.Context, *ExecutionReq) (*ExecutionLogsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecutionLogs not implemented")
}
func (UnimplementedWorkflowRpcServer) mustEmbedUnimplementedWorkflowRpcServer() {}
func (UnimplementedWorkflowRpcServer) testEmbeddedByValue()                     {}

// UnsafeWorkflowRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowRpcServer will
// result in compilation errors.
type UnsafeWorkflowRpcServer interface {
	mustEmbedUnimplementedWorkflowRpcServer()
}

func RegisterWorkflowRpcServer(s grpc.ServiceRegistrar, srv WorkflowRpcServer) {
	// If the following call pancis, it indicates UnimplementedWorkflowRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowRpc_ServiceDesc, srv)
}

func _WorkflowRpc_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).RefreshToken(ctx, req.(*RefreshTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_Me_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).Me(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_Me_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).Me(ctx, req.(*MeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_CreateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkflowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).CreateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_CreateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).CreateWorkflow(ctx, req.(*CreateWorkflowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_ListWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).ListWorkflows(ctx, req.(*ListWorkflowsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_GetWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).GetWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_GetWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).GetWorkflow(ctx, req.(*WorkflowByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_UpdateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkflowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).UpdateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_UpdateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).UpdateWorkflow(ctx, req.(*UpdateWorkflowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_DeleteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).DeleteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_DeleteWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).DeleteWorkflow(ctx, req.(*WorkflowByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_SaveWorkflowDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDraftReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).SaveWorkflowDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_SaveWorkflowDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).SaveWorkflowDraft(ctx, req.(*SaveDraftReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_PublishWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).PublishWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_PublishWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).PublishWorkflow(ctx, req.(*PublishReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_ListWorkflowVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVersionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).ListWorkflowVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_ListWorkflowVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).ListWorkflowVersions(ctx, req.(*ListVersionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_RollbackWorkflowVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).RollbackWorkflowVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_RollbackWorkflowVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).RollbackWorkflowVersion(ctx, req.(*RollbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_ExecuteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).ExecuteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_ExecuteWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).ExecuteWorkflow(ctx, req.(*ExecuteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_DebugWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).DebugWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_DebugWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).DebugWorkflow(ctx, req.(*ExecuteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_GetExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).GetExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_GetExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).GetExecution(ctx, req.(*ExecutionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowRpc_GetExecutionLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowRpcServer).GetExecutionLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowRpc_GetExecutionLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowRpcServer).GetExecutionLogs(ctx, req.(*ExecutionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowRpc_ServiceDesc is the grpc.ServiceDesc for WorkflowRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workflow.WorkflowRpc",
	HandlerType: (*WorkflowRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _WorkflowRpc_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _WorkflowRpc_Login_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _WorkflowRpc_RefreshToken_Handler,
		},
		{
			MethodName: "Me",
			Handler:    _WorkflowRpc_Me_Handler,
		},
		{
			MethodName: "CreateWorkflow",
			Handler:    _WorkflowRpc_CreateWorkflow_Handler,
		},
		{
			MethodName: "ListWorkflows",
			Handler:    _WorkflowRpc_ListWorkflows_Handler,
		},
		{
			MethodName: "GetWorkflow",
			Handler:    _WorkflowRpc_GetWorkflow_Handler,
		},
		{
			MethodName: "UpdateWorkflow",
			Handler:    _WorkflowRpc_UpdateWorkflow_Handler,
		},
		{
			MethodName: "DeleteWorkflow",
			Handler:    _WorkflowRpc_DeleteWorkflow_Handler,
		},
		{
			MethodName: "SaveWorkflowDraft",
			Handler:    _WorkflowRpc_SaveWorkflowDraft_Handler,
		},
		{
			MethodName: "PublishWorkflow",
			Handler:    _WorkflowRpc_PublishWorkflow_Handler,
		},
		{
			MethodName: "ListWorkflowVersions",
			Handler:    _WorkflowRpc_ListWorkflowVersions_Handler,
		},
		{
			MethodName: "RollbackWorkflowVersion",
			Handler:    _WorkflowRpc_RollbackWorkflowVersion_Handler,
		},
		{
			MethodName: "ExecuteWorkflow",
			Handler:    _WorkflowRpc_ExecuteWorkflow_Handler,
		},
		{
			MethodName: "DebugWorkflow",
			Handler:    _WorkflowRpc_DebugWorkflow_Handler,
		},
		{
			MethodName: "GetExecution",
			Handler:    _WorkflowRpc_GetExecution_Handler,
		},
		{
			MethodName: "GetExecutionLogs",
			Handler:    _WorkflowRpc_GetExecutionLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/workflow/workflow.proto",
}
