// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: workflow.proto

package server

import (
	"context"

	"zilo/backend/rpc/workflow/internal/logic"
	"zilo/backend/rpc/workflow/internal/svc"
	"zilo/backend/rpc/workflow/workflowpb"
)

type WorkflowRpcServer struct {
	svcCtx *svc.ServiceContext
	workflowpb.UnimplementedWorkflowRpcServer
}

func NewWorkflowRpcServer(svcCtx *svc.ServiceContext) *WorkflowRpcServer {
	return &WorkflowRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *WorkflowRpcServer) Register(ctx context.Context, in *workflowpb.RegisterReq) (*workflowpb.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *WorkflowRpcServer) Login(ctx context.Context, in *workflowpb.LoginReq) (*workflowpb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *WorkflowRpcServer) RefreshToken(ctx context.Context, in *workflowpb.RefreshTokenReq) (*workflowpb.RefreshTokenResp, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *WorkflowRpcServer) Me(ctx context.Context, in *workflowpb.MeReq) (*workflowpb.MeResp, error) {
	l := logic.NewMeLogic(ctx, s.svcCtx)
	return l.Me(in)
}

func (s *WorkflowRpcServer) CreateWorkflow(ctx context.Context, in *workflowpb.CreateWorkflowReq) (*workflowpb.WorkflowResp, error) {
	l := logic.NewCreateWorkflowLogic(ctx, s.svcCtx)
	return l.CreateWorkflow(in)
}

func (s *WorkflowRpcServer) ListWorkflows(ctx context.Context, in *workflowpb.ListWorkflowsReq) (*workflowpb.ListWorkflowsResp, error) {
	l := logic.NewListWorkflowsLogic(ctx, s.svcCtx)
	return l.ListWorkflows(in)
}

func (s *WorkflowRpcServer) GetWorkflow(ctx context.Context, in *workflowpb.WorkflowByIdReq) (*workflowpb.WorkflowResp, error) {
	l := logic.NewGetWorkflowLogic(ctx, s.svcCtx)
	return l.GetWorkflow(in)
}

func (s *WorkflowRpcServer) UpdateWorkflow(ctx context.Context, in *workflowpb.UpdateWorkflowReq) (*workflowpb.WorkflowResp, error) {
	l := logic.NewUpdateWorkflowLogic(ctx, s.svcCtx)
	return l.UpdateWorkflow(in)
}

func (s *WorkflowRpcServer) DeleteWorkflow(ctx context.Context, in *workflowpb.WorkflowByIdReq) (*workflowpb.Empty, error) {
	l := logic.NewDeleteWorkflowLogic(ctx, s.svcCtx)
	return l.DeleteWorkflow(in)
}

func (s *WorkflowRpcServer) SaveWorkflowDraft(ctx context.Context, in *workflowpb.SaveDraftReq) (*workflowpb.Empty, error) {
	l := logic.NewSaveWorkflowDraftLogic(ctx, s.svcCtx)
	return l.SaveWorkflowDraft(in)
}

func (s *WorkflowRpcServer) PublishWorkflow(ctx context.Context, in *workflowpb.PublishReq) (*workflowpb.PublishResp, error) {
	l := logic.NewPublishWorkflowLogic(ctx, s.svcCtx)
	return l.PublishWorkflow(in)
}

func (s *WorkflowRpcServer) ListWorkflowVersions(ctx context.Context, in *workflowpb.ListVersionsReq) (*workflowpb.ListVersionsResp, error) {
	l := logic.NewListWorkflowVersionsLogic(ctx, s.svcCtx)
	return l.ListWorkflowVersions(in)
}

func (s *WorkflowRpcServer) RollbackWorkflowVersion(ctx context.Context, in *workflowpb.RollbackReq) (*workflowpb.Empty, error) {
	l := logic.NewRollbackWorkflowVersionLogic(ctx, s.svcCtx)
	return l.RollbackWorkflowVersion(in)
}

func (s *WorkflowRpcServer) ExecuteWorkflow(ctx context.Context, in *workflowpb.ExecuteReq) (*workflowpb.ExecuteResp, error) {
	l := logic.NewExecuteWorkflowLogic(ctx, s.svcCtx)
	return l.ExecuteWorkflow(in)
}

func (s *WorkflowRpcServer) DebugWorkflow(ctx context.Context, in *workflowpb.ExecuteReq) (*workflowpb.ExecuteResp, error) {
	l := logic.NewDebugWorkflowLogic(ctx, s.svcCtx)
	return l.DebugWorkflow(in)
}

func (s *WorkflowRpcServer) GetExecution(ctx context.Context, in *workflowpb.ExecutionReq) (*workflowpb.ExecutionResp, error) {
	l := logic.NewGetExecutionLogic(ctx, s.svcCtx)
	return l.GetExecution(in)
}

func (s *WorkflowRpcServer) GetExecutionLogs(ctx context.Context, in *workflowpb.ExecutionReq) (*workflowpb.ExecutionLogsResp, error) {
	l := logic.NewGetExecutionLogsLogic(ctx, s.svcCtx)
	return l.GetExecutionLogs(in)
}
