// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: workflow.proto

package workflowrpc

import (
	"context"

	"zilo/backend/rpc/workflow/workflowpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateWorkflowReq = workflowpb.CreateWorkflowReq
	Empty             = workflowpb.Empty
	ExecuteReq        = workflowpb.ExecuteReq
	ExecuteResp       = workflowpb.ExecuteResp
	ExecutionLogItem  = workflowpb.ExecutionLogItem
	ExecutionLogsResp = workflowpb.ExecutionLogsResp
	ExecutionReq      = workflowpb.ExecutionReq
	ExecutionResp     = workflowpb.ExecutionResp
	ListVersionsReq   = workflowpb.ListVersionsReq
	ListVersionsResp  = workflowpb.ListVersionsResp
	ListWorkflowsReq  = workflowpb.ListWorkflowsReq
	ListWorkflowsResp = workflowpb.ListWorkflowsResp
	LoginReq          = workflowpb.LoginReq
	LoginResp         = workflowpb.LoginResp
	MeReq             = workflowpb.MeReq
	MeResp            = workflowpb.MeResp
	PublishReq        = workflowpb.PublishReq
	PublishResp       = workflowpb.PublishResp
	RefreshTokenReq   = workflowpb.RefreshTokenReq
	RefreshTokenResp  = workflowpb.RefreshTokenResp
	RegisterReq       = workflowpb.RegisterReq
	RegisterResp      = workflowpb.RegisterResp
	RollbackReq       = workflowpb.RollbackReq
	SaveDraftReq      = workflowpb.SaveDraftReq
	UpdateWorkflowReq = workflowpb.UpdateWorkflowReq
	VersionItem       = workflowpb.VersionItem
	WorkflowByIdReq   = workflowpb.WorkflowByIdReq
	WorkflowResp      = workflowpb.WorkflowResp

	WorkflowRpc interface {
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
		Me(ctx context.Context, in *MeReq, opts ...grpc.CallOption) (*MeResp, error)
		CreateWorkflow(ctx context.Context, in *CreateWorkflowReq, opts ...grpc.CallOption) (*WorkflowResp, error)
		ListWorkflows(ctx context.Context, in *ListWorkflowsReq, opts ...grpc.CallOption) (*ListWorkflowsResp, error)
		GetWorkflow(ctx context.Context, in *WorkflowByIdReq, opts ...grpc.CallOption) (*WorkflowResp, error)
		UpdateWorkflow(ctx context.Context, in *UpdateWorkflowReq, opts ...grpc.CallOption) (*WorkflowResp, error)
		DeleteWorkflow(ctx context.Context, in *WorkflowByIdReq, opts ...grpc.CallOption) (*Empty, error)
		SaveWorkflowDraft(ctx context.Context, in *SaveDraftReq, opts ...grpc.CallOption) (*Empty, error)
		PublishWorkflow(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResp, error)
		ListWorkflowVersions(ctx context.Context, in *ListVersionsReq, opts ...grpc.CallOption) (*ListVersionsResp, error)
		RollbackWorkflowVersion(ctx context.Context, in *RollbackReq, opts ...grpc.CallOption) (*Empty, error)
		ExecuteWorkflow(ctx context.Context, in *ExecuteReq, opts ...grpc.CallOption) (*ExecuteResp, error)
		DebugWorkflow(ctx context.Context, in *ExecuteReq, opts ...grpc.CallOption) (*ExecuteResp, error)
		GetExecution(ctx context.Context, in *ExecutionReq, opts ...grpc.CallOption) (*ExecutionResp, error)
		GetExecutionLogs(ctx context.Context, in *ExecutionReq, opts ...grpc.CallOption) (*ExecutionLogsResp, error)
	}

	defaultWorkflowRpc struct {
		cli zrpc.Client
	}
)

func NewWorkflowRpc(cli zrpc.Client) WorkflowRpc {
	return &defaultWorkflowRpc{
		cli: cli,
	}
}

func (m *defaultWorkflowRpc) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) Me(ctx context.Context, in *MeReq, opts ...grpc.CallOption) (*MeResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.Me(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) CreateWorkflow(ctx context.Context, in *CreateWorkflowReq, opts ...grpc.CallOption) (*WorkflowResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.CreateWorkflow(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) ListWorkflows(ctx context.Context, in *ListWorkflowsReq, opts ...grpc.CallOption) (*ListWorkflowsResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.ListWorkflows(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) GetWorkflow(ctx context.Context, in *WorkflowByIdReq, opts ...grpc.CallOption) (*WorkflowResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.GetWorkflow(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) UpdateWorkflow(ctx context.Context, in *UpdateWorkflowReq, opts ...grpc.CallOption) (*WorkflowResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.UpdateWorkflow(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) DeleteWorkflow(ctx context.Context, in *WorkflowByIdReq, opts ...grpc.CallOption) (*Empty, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.DeleteWorkflow(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) SaveWorkflowDraft(ctx context.Context, in *SaveDraftReq, opts ...grpc.CallOption) (*Empty, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.SaveWorkflowDraft(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) PublishWorkflow(ctx context.Context, in *PublishReq, opts ...grpc.CallOption) (*PublishResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.PublishWorkflow(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) ListWorkflowVersions(ctx context.Context, in *ListVersionsReq, opts ...grpc.CallOption) (*ListVersionsResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.ListWorkflowVersions(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) RollbackWorkflowVersion(ctx context.Context, in *RollbackReq, opts ...grpc.CallOption) (*Empty, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.RollbackWorkflowVersion(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) ExecuteWorkflow(ctx context.Context, in *ExecuteReq, opts ...grpc.CallOption) (*ExecuteResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.ExecuteWorkflow(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) DebugWorkflow(ctx context.Context, in *ExecuteReq, opts ...grpc.CallOption) (*ExecuteResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.DebugWorkflow(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) GetExecution(ctx context.Context, in *ExecutionReq, opts ...grpc.CallOption) (*ExecutionResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.GetExecution(ctx, in, opts...)
}

func (m *defaultWorkflowRpc) GetExecutionLogs(ctx context.Context, in *ExecutionReq, opts ...grpc.CallOption) (*ExecutionLogsResp, error) {
	client := workflowpb.NewWorkflowRpcClient(m.cli.Conn())
	return client.GetExecutionLogs(ctx, in, opts...)
}
