// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateWorkflowReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
}

type ExecuteReq struct {
	InputJson string `json:"inputJson,optional"`
}

type ExecuteResp struct {
	ExecutionId int64  `json:"executionId"`
	Status      string `json:"status"`
}

type ExecutionLogItem struct {
	NodeId     string `json:"nodeId"`
	NodeType   string `json:"nodeType"`
	Status     string `json:"status"`
	InputJson  string `json:"inputJson"`
	OutputJson string `json:"outputJson"`
	ErrorMsg   string `json:"errorMsg"`
	StartedAt  string `json:"startedAt"`
	EndedAt    string `json:"endedAt"`
	DurationMs int64  `json:"durationMs"`
}

type ExecutionLogsResp struct {
	List []ExecutionLogItem `json:"list"`
}

type ExecutionResp struct {
	Id         int64  `json:"id"`
	WorkflowId int64  `json:"workflowId"`
	VersionId  int64  `json:"versionId"`
	Status     string `json:"status"`
	InputJson  string `json:"inputJson"`
	OutputJson string `json:"outputJson"`
	ErrorMsg   string `json:"errorMsg"`
	StartedAt  string `json:"startedAt"`
	EndedAt    string `json:"endedAt"`
	DurationMs int64  `json:"durationMs"`
}

type ListWorkflowsReq struct {
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
	Keyword  string `form:"keyword,optional"`
}

type ListWorkflowsResp struct {
	Total int64          `json:"total"`
	List  []WorkflowResp `json:"list"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpireAt     int64  `json:"expireAt"`
}

type MeResp struct {
	UserId   int64  `json:"userId"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
}

type PublishReq struct {
	Note string `json:"note,optional"`
}

type PublishResp struct {
	Version int64 `json:"version"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResp struct {
	AccessToken string `json:"accessToken"`
	ExpireAt    int64  `json:"expireAt"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Nickname string `json:"nickname,optional"`
}

type RegisterResp struct {
	UserId int64  `json:"userId"`
	Email  string `json:"email"`
}

type SaveDraftReq struct {
	DslJson string `json:"dslJson"`
}

type UpdateWorkflowReq struct {
	Name        string `json:"name,optional"`
	Description string `json:"description,optional"`
}

type VersionItem struct {
	Id          int64  `json:"id"`
	Version     int64  `json:"version"`
	IsPublished bool   `json:"isPublished"`
	CreatedAt   string `json:"createdAt"`
}

type VersionsResp struct {
	List []VersionItem `json:"list"`
}

type WorkflowResp struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	Status        int64  `json:"status"`
	LatestVersion int64  `json:"latestVersion"`
	CreatedAt     string `json:"createdAt"`
	UpdatedAt     string `json:"updatedAt"`
}
