// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	workflowVersionsFieldNames          = builder.RawFieldNames(&WorkflowVersions{})
	workflowVersionsRows                = strings.Join(workflowVersionsFieldNames, ",")
	workflowVersionsRowsExpectAutoSet   = strings.Join(stringx.Remove(workflowVersionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workflowVersionsRowsWithPlaceHolder = strings.Join(stringx.Remove(workflowVersionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	workflowVersionsModel interface {
		Insert(ctx context.Context, data *WorkflowVersions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*WorkflowVersions, error)
		FindOneByWorkflowIdVersion(ctx context.Context, workflowId uint64, version int64) (*WorkflowVersions, error)
		Update(ctx context.Context, data *WorkflowVersions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultWorkflowVersionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WorkflowVersions struct {
		Id          uint64    `db:"id"`
		WorkflowId  uint64    `db:"workflow_id"`
		Version     int64     `db:"version"`
		DslJson     string    `db:"dsl_json"`
		IsPublished int64     `db:"is_published"`
		CreatedBy   uint64    `db:"created_by"`
		CreatedAt   time.Time `db:"created_at"`
	}
)

func newWorkflowVersionsModel(conn sqlx.SqlConn) *defaultWorkflowVersionsModel {
	return &defaultWorkflowVersionsModel{
		conn:  conn,
		table: "`workflow_versions`",
	}
}

func (m *defaultWorkflowVersionsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWorkflowVersionsModel) FindOne(ctx context.Context, id uint64) (*WorkflowVersions, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workflowVersionsRows, m.table)
	var resp WorkflowVersions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkflowVersionsModel) FindOneByWorkflowIdVersion(ctx context.Context, workflowId uint64, version int64) (*WorkflowVersions, error) {
	var resp WorkflowVersions
	query := fmt.Sprintf("select %s from %s where `workflow_id` = ? and `version` = ? limit 1", workflowVersionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, workflowId, version)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkflowVersionsModel) Insert(ctx context.Context, data *WorkflowVersions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, workflowVersionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.WorkflowId, data.Version, data.DslJson, data.IsPublished, data.CreatedBy)
	return ret, err
}

func (m *defaultWorkflowVersionsModel) Update(ctx context.Context, newData *WorkflowVersions) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, workflowVersionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.WorkflowId, newData.Version, newData.DslJson, newData.IsPublished, newData.CreatedBy, newData.Id)
	return err
}

func (m *defaultWorkflowVersionsModel) tableName() string {
	return m.table
}
