// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	workflowExecutionsFieldNames          = builder.RawFieldNames(&WorkflowExecutions{})
	workflowExecutionsRows                = strings.Join(workflowExecutionsFieldNames, ",")
	workflowExecutionsRowsExpectAutoSet   = strings.Join(stringx.Remove(workflowExecutionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workflowExecutionsRowsWithPlaceHolder = strings.Join(stringx.Remove(workflowExecutionsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	workflowExecutionsModel interface {
		Insert(ctx context.Context, data *WorkflowExecutions) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*WorkflowExecutions, error)
		Update(ctx context.Context, data *WorkflowExecutions) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultWorkflowExecutionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WorkflowExecutions struct {
		Id          uint64         `db:"id"`
		WorkflowId  uint64         `db:"workflow_id"`
		VersionId   uint64         `db:"version_id"`
		TriggerType string         `db:"trigger_type"`
		Status      string         `db:"status"`
		InputJson   sql.NullString `db:"input_json"`
		OutputJson  sql.NullString `db:"output_json"`
		ErrorMsg    sql.NullString `db:"error_msg"`
		StartedAt   sql.NullTime   `db:"started_at"`
		EndedAt     sql.NullTime   `db:"ended_at"`
		DurationMs  int64          `db:"duration_ms"`
		CreatedAt   time.Time      `db:"created_at"`
	}
)

func newWorkflowExecutionsModel(conn sqlx.SqlConn) *defaultWorkflowExecutionsModel {
	return &defaultWorkflowExecutionsModel{
		conn:  conn,
		table: "`workflow_executions`",
	}
}

func (m *defaultWorkflowExecutionsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWorkflowExecutionsModel) FindOne(ctx context.Context, id uint64) (*WorkflowExecutions, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workflowExecutionsRows, m.table)
	var resp WorkflowExecutions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkflowExecutionsModel) Insert(ctx context.Context, data *WorkflowExecutions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, workflowExecutionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.WorkflowId, data.VersionId, data.TriggerType, data.Status, data.InputJson, data.OutputJson, data.ErrorMsg, data.StartedAt, data.EndedAt, data.DurationMs)
	return ret, err
}

func (m *defaultWorkflowExecutionsModel) Update(ctx context.Context, data *WorkflowExecutions) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, workflowExecutionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.WorkflowId, data.VersionId, data.TriggerType, data.Status, data.InputJson, data.OutputJson, data.ErrorMsg, data.StartedAt, data.EndedAt, data.DurationMs, data.Id)
	return err
}

func (m *defaultWorkflowExecutionsModel) tableName() string {
	return m.table
}
