// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	workflowsFieldNames          = builder.RawFieldNames(&Workflows{})
	workflowsRows                = strings.Join(workflowsFieldNames, ",")
	workflowsRowsExpectAutoSet   = strings.Join(stringx.Remove(workflowsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workflowsRowsWithPlaceHolder = strings.Join(stringx.Remove(workflowsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	workflowsModel interface {
		Insert(ctx context.Context, data *Workflows) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Workflows, error)
		Update(ctx context.Context, data *Workflows) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultWorkflowsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Workflows struct {
		Id            uint64    `db:"id"`
		OwnerId       uint64    `db:"owner_id"`
		Name          string    `db:"name"`
		Description   string    `db:"description"`
		Status        int64     `db:"status"`
		LatestVersion int64     `db:"latest_version"`
		CreatedAt     time.Time `db:"created_at"`
		UpdatedAt     time.Time `db:"updated_at"`
	}
)

func newWorkflowsModel(conn sqlx.SqlConn) *defaultWorkflowsModel {
	return &defaultWorkflowsModel{
		conn:  conn,
		table: "`workflows`",
	}
}

func (m *defaultWorkflowsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWorkflowsModel) FindOne(ctx context.Context, id uint64) (*Workflows, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workflowsRows, m.table)
	var resp Workflows
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkflowsModel) Insert(ctx context.Context, data *Workflows) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, workflowsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OwnerId, data.Name, data.Description, data.Status, data.LatestVersion)
	return ret, err
}

func (m *defaultWorkflowsModel) Update(ctx context.Context, data *Workflows) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, workflowsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OwnerId, data.Name, data.Description, data.Status, data.LatestVersion, data.Id)
	return err
}

func (m *defaultWorkflowsModel) tableName() string {
	return m.table
}
