// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	workflowExecutionLogsFieldNames          = builder.RawFieldNames(&WorkflowExecutionLogs{})
	workflowExecutionLogsRows                = strings.Join(workflowExecutionLogsFieldNames, ",")
	workflowExecutionLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(workflowExecutionLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workflowExecutionLogsRowsWithPlaceHolder = strings.Join(stringx.Remove(workflowExecutionLogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	workflowExecutionLogsModel interface {
		Insert(ctx context.Context, data *WorkflowExecutionLogs) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*WorkflowExecutionLogs, error)
		Update(ctx context.Context, data *WorkflowExecutionLogs) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultWorkflowExecutionLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	WorkflowExecutionLogs struct {
		Id          uint64         `db:"id"`
		ExecutionId uint64         `db:"execution_id"`
		NodeId      string         `db:"node_id"`
		NodeType    string         `db:"node_type"`
		Status      string         `db:"status"`
		InputJson   sql.NullString `db:"input_json"`
		OutputJson  sql.NullString `db:"output_json"`
		ErrorMsg    sql.NullString `db:"error_msg"`
		StartedAt   sql.NullTime   `db:"started_at"`
		EndedAt     sql.NullTime   `db:"ended_at"`
		DurationMs  int64          `db:"duration_ms"`
		CreatedAt   time.Time      `db:"created_at"`
	}
)

func newWorkflowExecutionLogsModel(conn sqlx.SqlConn) *defaultWorkflowExecutionLogsModel {
	return &defaultWorkflowExecutionLogsModel{
		conn:  conn,
		table: "`workflow_execution_logs`",
	}
}

func (m *defaultWorkflowExecutionLogsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWorkflowExecutionLogsModel) FindOne(ctx context.Context, id uint64) (*WorkflowExecutionLogs, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workflowExecutionLogsRows, m.table)
	var resp WorkflowExecutionLogs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkflowExecutionLogsModel) Insert(ctx context.Context, data *WorkflowExecutionLogs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, workflowExecutionLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ExecutionId, data.NodeId, data.NodeType, data.Status, data.InputJson, data.OutputJson, data.ErrorMsg, data.StartedAt, data.EndedAt, data.DurationMs)
	return ret, err
}

func (m *defaultWorkflowExecutionLogsModel) Update(ctx context.Context, data *WorkflowExecutionLogs) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, workflowExecutionLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ExecutionId, data.NodeId, data.NodeType, data.Status, data.InputJson, data.OutputJson, data.ErrorMsg, data.StartedAt, data.EndedAt, data.DurationMs, data.Id)
	return err
}

func (m *defaultWorkflowExecutionLogsModel) tableName() string {
	return m.table
}
